name: Unit

on:
  push:
    branches:
      - main
      - v*-branch
  pull_request:
    types:
      - opened
      - reopened
      - synchronize
    branches:
      - main
      - v*-branch

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.sha }}
  cancel-in-progress: true

jobs:
  unit-test:
    env:
      platforms: -p unit_testing -p native_sim
      roots: -T tt-zephyr-platforms/tests -T tt-zephyr-platforms/samples
    strategy:
      fail-fast: false
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v4
        with:
          path: tt-zephyr-platforms
      - uses: ./tt-zephyr-platforms/.github/workflows/prepare-zephyr
        with:
          app-path: tt-zephyr-platforms

      - id: build
        shell: bash
        run: |
          west twister -i --build-only $platforms $roots

      - id: run
        shell: bash
        run: |
          west twister -i --run-only $platforms $roots -v

      - name: Upload test results
        if: ${{ always() }}
        uses: actions/upload-artifact@v4
        with:
          name: unit-test-results
          path: |
            twister-out/**/.config
            twister-out/**/devicetree_generated.h
            twister-out/**/zephyr.bin
            twister-out/**/zephyr.dts
            twister-out/**/zephyr.elf
            twister-out/**/zephyr.map
            twister-out/**/zephyr.stat
            twister-out/**/handler.log
            twister-out/twister.log
            twister-out/twister.json

  tt-sim-test:
    env:
      platforms: -p native_sim/native/64
      tags: --tag tt_sim
      configroots: --alt-config-root tt-zephyr-platforms/test-conf
      roots: -T zephyr
    strategy:
      fail-fast: false
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v4
        with:
          path: tt-zephyr-platforms
      - uses: ./tt-zephyr-platforms/.github/workflows/prepare-zephyr
        with:
          app-path: tt-zephyr-platforms

      - name: build and run
        shell: bash
        run: |
          west twister -i $platforms $tags $configroots $roots

      - name: Upload test results
        if: ${{ always() }}
        uses: actions/upload-artifact@v4
        with:
          name: tt-sim-test-results
          path: |
            twister-out/**/.config
            twister-out/**/devicetree_generated.h
            twister-out/**/zephyr.bin
            twister-out/**/zephyr.dts
            twister-out/**/zephyr.elf
            twister-out/**/zephyr.map
            twister-out/**/zephyr.stat
            twister-out/**/handler.log
            twister-out/twister.log
            twister-out/twister.json
